name: ManUtdFreedomModRevamped
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 0.1 BETA
description: Plugin for the ManUtdFreedom server.
softdepend: [BukkitTelnet, WorldEdit, Essentials]
author(s): [DarthSalmon, Madgeek]

# plugin.yml is no longer used to define commands.
