name: ManUtdFreedomModRevamped
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 0.1 BETA
description: Plugin for the ManUtdFreedom server.
softdepend: [BukkitTelnet, WorldEdit, Essentials]
authors: [Madgeek1450, Prozza]

# plugin.yml is no longer used to define commands.
